apiVersion: apps/v1
kind: Deployment
metadata:
  name: componente-patrones
  labels:
    app: componente-patrones
spec:
  selector:
    matchLabels:
      app: componente-patrones
  template:
    metadata:
      labels:
        app: componente-patrones
    spec:
      containers:
        - image: 'danielsabana/componente_patrones:0.0.0'
          name: componente-patrones
          ports:
            - containerPort: 3000