apiVersion: apps/v1
kind: Deployment
metadata:
  name: componente-patrones
  labels:
    app: componente-patrones
spec:
  selector:
    matchLabels:
      app: componente-patrones
  template:
    metadata:
      labels:
        app: componente-patrones
    spec:
      containers:
        - image: 'davidh120/python-rest-api:63c08087921e8b403a483604d76c587d9ccaf7d7'
          name: componente-patrones
          ports:
            - containerPort: 3000